# Generated by Django 5.1.7 on 2025-04-03 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rest_det',
            fields=[
                ('username', models.CharField(max_length=75)),
                ('email', models.EmailField(max_length=254)),
                ('rest_id', models.CharField(max_length=75, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=75)),
            ],
        ),
    ]
