# Generated by Django 5.1.7 on 2025-04-18 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_rest_det_options_alter_rest_det_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rest_det',
            options={},
        ),
        migrations.AlterModelManagers(
            name='rest_det',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='rest_det',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='rest_det',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='rest_det',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='rest_det',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='rest_det',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='rest_det',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='rest_det',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='rest_det',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='rest_det',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='rest_det',
            name='username',
            field=models.CharField(max_length=75),
        ),
    ]
