# Generated by Django 5.1.7 on 2025-04-17 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0003_alter_orders_restaurant'),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='restaurant',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='User.rest_det'),
        ),
    ]
