# Generated by Django 5.1.7 on 2025-04-18 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_alter_rest_det_options_alter_rest_det_managers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rest_det',
            old_name='username',
            new_name='USERNAME_FIELD',
        ),
    ]
