# Generated by Django 5.1.7 on 2025-04-18 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_rename_username_rest_det_username_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rest_det',
            old_name='USERNAME_FIELD',
            new_name='username',
        ),
        migrations.AddField(
            model_name='rest_det',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
