# Generated by Django 5.1.7 on 2025-05-09 19:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_remove_restaurantprofile_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffprofile',
            old_name='extension_number',
            new_name='Contact_number',
        ),
        migrations.RenameField(
            model_name='staffprofile',
            old_name='department',
            new_name='Restaurant_location',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='office_location',
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='Restaurant_id',
            field=models.IntegerField(default=True, unique=True, validators=[django.core.validators.MinLengthValidator(5, 'Phone number must be 10 digits.'), django.core.validators.MaxLengthValidator(5, 'Phone number must be 10 digits.')]),
        ),
    ]
