# Generated by Django 5.1.7 on 2025-05-09 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_rename_extension_number_staffprofile_contact_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regularuserprofile',
            old_name='phone_number',
            new_name='contact_number',
        ),
    ]
