# Generated by Django 5.1.7 on 2025-05-09 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_rename_phone_number_regularuserprofile_contact_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regularuserprofile',
            old_name='contact_number',
            new_name='Contact_number',
        ),
    ]
