# Generated by Django 5.1.7 on 2025-05-09 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0012_staffprofile_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffprofile',
            name='department',
        ),
    ]
