# Generated by Django 5.1.7 on 2025-05-10 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0013_remove_staffprofile_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='Restaurant_name',
            field=models.CharField(default=False, max_length=25),
        ),
    ]
