# Generated by Django 5.1.7 on 2025-05-10 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0014_staffprofile_restaurant_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularuserprofile',
            name='Contact_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='Restaurant_id',
            field=models.IntegerField(default=True, unique=True),
        ),
    ]
