# Generated by Django 5.1.7 on 2025-05-10 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0007_delete_order_orders_quantity_orders_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='uuid',
            field=models.UUIDField(default=1),
        ),
    ]
