# Generated by Django 5.1.7 on 2025-05-10 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0008_alter_orders_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='uuid',
        ),
    ]
