# Generated by Django 5.1.7 on 2025-05-11 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0009_remove_orders_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='quantity',
        ),
    ]
